name: Hono Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install --frozen-lockfile
      - name: Install Bombardier
        run: sudo apt-get install -y bombardier
      - name: Run Performance Test
        run: bombardier -c 10 -n 10000 http://localhost:3000 